name: Lint da code ✨
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop -c "make" "lint"

    # NOTE: When I was not using nix flakes, was using the following
    #   - uses: actions/setup-go@v4
    #     with:
    #       go-version: "~1.20.4"
    #       check-latest: true
    #   - uses: actions/checkout@v4
    #   - name: golangci-lint
    #     uses: golangci/golangci-lint-action@v3.7.0
    #     with:
    #       args: --timeout 10m
